global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "core-banking-api-job"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "pismo-core-banking-api"